import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { Http,HttpModule } from '@angular/http';

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { MatToolbarModule, MatIconModule, MatSidenavModule, MatListModule, MatButtonModule,MatCheckboxModule } from  '@angular/material';
import { 
        MatCardModule, MatInputModule,MatFormFieldModule, MatProgressSpinnerModule,MatBadgeModule,MatSelectModule,MatRadioModule,
MatDatepickerModule,MatNativeDateModule,MatChipsModule,MatTooltipModule,MatTableModule,MatPaginatorModule} from  '@angular/material';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import {MatGridListModule} from '@angular/material/grid-list';
import {MatSlideToggleModule} from '@angular/material/slide-toggle';
import {MatDialogModule} from '@angular/material/dialog';

import 'hammerjs';
import { NavBarComponent } from '@src/app/components/nav-bar/nav-bar.component';
import { LoginComponent } from '@src/app/components/login/login.component';

import {LoginService} from '@src/app/services/login.service';
import {AddBookService} from '@src/app/services/add-book.service';
import {GetBookListServiceService} from '@src/app/services/get-book-list-service.service';
import {GetBookService} from '@src/app/services/get-book.service';
import {EditBookService} from '@src/app/services/edit-book.service';
import {RemoveBookService} from '@src/app/services/remove-book.service';

import { HomeComponent } from '@src/app/components/home/home.component';
import { RegisterComponent } from '@src/app/components/register/register.component';
import { BookComponent } from '@src/app/components/book/book.component';
import { AddBookComponent } from '@src/app/components/add-book/add-book.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';

import { DateAdapter, MAT_DATE_FORMATS, MAT_DATE_LOCALE } from '@angular/material';
import {MomentDateAdapter } from '@angular/material-moment-adapter';
import { BookListComponent, DialogOverviewExampleDialog } from '@src/app/components/book-list/book-list.component';
import { ViewBookComponent } from '@src/app/components/view-book/view-book.component';
import { EditBookComponent } from '@src/app/components/edit-book/edit-book.component';

export const DateFormats = {
  parse: {
      dateInput: ['YYYY-MM-DD']
  },
  display: {
      dateInput: 'YYYY-MM-DD',
      monthYearLabel: 'MMM YYYY',
      dateA11yLabel: 'LL',
      monthYearA11yLabel: 'MMMM YYYY',
  },
};

@NgModule({
  declarations: [
    AppComponent,
    NavBarComponent,
    LoginComponent,
    HomeComponent,
    RegisterComponent,
    BookComponent,
    AddBookComponent,
    AutoGeneratedComponent,
    BookListComponent, DialogOverviewExampleDialog,
    ViewBookComponent,
    EditBookComponent
   
  ],
  imports: [
    BrowserAnimationsModule,
    BrowserModule,
    HttpClientModule,
    HttpModule,
    MatDialogModule,
    AppRoutingModule,
    MatButtonModule,
    MatCheckboxModule,
    MatToolbarModule, 
    MatIconModule, 
    MatSidenavModule, 
    MatListModule,
    MatInputModule,
    MatCardModule,
    ReactiveFormsModule,
    MatFormFieldModule,
    FormsModule,
    MatProgressSpinnerModule,
    MatGridListModule,MatBadgeModule,MatSelectModule,MatRadioModule,
    MatDatepickerModule,MatNativeDateModule,MatChipsModule,MatTooltipModule,MatTableModule,MatPaginatorModule,
    MatSlideToggleModule
  ],
    entryComponents: [DialogOverviewExampleDialog],
    providers: [
    LoginService,Http,AddBookService,GetBookListServiceService,GetBookService,EditBookService,RemoveBookService,
    { provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE] },
          { provide: MAT_DATE_FORMATS, useValue: DateFormats }
  ],
  bootstrap: [AppComponent, DialogOverviewExampleDialog]
})
export class AppModule { }
