amazonProperties:
   endpointUrl: https://363831971299.signin.aws.amazon.com/console
   accessKey: xxxxxxx
   secretKey: xxxxxxx
   bucketName: mw-healthy-docs
spring:
 servlet:
  multipart:
   max-file-size: 100MB
   max-request-size: 100MB
